export const queryKeys = {
  trees: ['trees'] as const,
  tree: (id: string) => ['trees', id] as const,
  treeDebugData: (treeId: string) => ['trees', treeId, 'debug'] as const,
  systemDebugData: ['debug', 'system'] as const,
  treeFiles: ['debug', 'treeFiles'] as const,
  individuals: ['individuals'] as const,
  individual: (id: string) => ['individuals', id] as const,
  families: ['families'] as const,
  family: (id: string) => ['families', id] as const,
  events: ['events'] as const,
  event: (id: string) => ['events', id] as const,
  eventTypes: ['eventTypes'] as const,
  places: ['places'] as const,
  place: (id: string) => ['places', id] as const,
  placeTypes: ['placeTypes'] as const,
  sources: ['sources'] as const,
  source: (id: string) => ['sources', id] as const,
  repositories: ['repositories'] as const,
  repository: (id: string) => ['repositories', id] as const,
  citations: (sourceId: string) => ['citations', sourceId] as const,
  citationsWithDetails: (sourceId: string) => ['citationsWithDetails', sourceId] as const,
  files: (sourceId: string) => ['files', sourceId] as const,
};
