/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as IndexImport } from './pages/index'
import { Route as PlacesIndexImport } from './pages/places/index'
import { Route as IndividualsIndexImport } from './pages/individuals/index'
import { Route as FamiliesIndexImport } from './pages/families/index'
import { Route as EventsIndexImport } from './pages/events/index'
import { Route as PlacesPlaceIdImport } from './pages/places/$placeId'
import { Route as IndividualsIndividualIdImport } from './pages/individuals/$individualId'
import { Route as FamiliesFamilyIdImport } from './pages/families/$familyId'
import { Route as EventsEventIdImport } from './pages/events/$eventId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PlacesIndexRoute = PlacesIndexImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => rootRoute,
} as any)

const IndividualsIndexRoute = IndividualsIndexImport.update({
  id: '/individuals/',
  path: '/individuals/',
  getParentRoute: () => rootRoute,
} as any)

const FamiliesIndexRoute = FamiliesIndexImport.update({
  id: '/families/',
  path: '/families/',
  getParentRoute: () => rootRoute,
} as any)

const EventsIndexRoute = EventsIndexImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRoute,
} as any)

const PlacesPlaceIdRoute = PlacesPlaceIdImport.update({
  id: '/places/$placeId',
  path: '/places/$placeId',
  getParentRoute: () => rootRoute,
} as any)

const IndividualsIndividualIdRoute = IndividualsIndividualIdImport.update({
  id: '/individuals/$individualId',
  path: '/individuals/$individualId',
  getParentRoute: () => rootRoute,
} as any)

const FamiliesFamilyIdRoute = FamiliesFamilyIdImport.update({
  id: '/families/$familyId',
  path: '/families/$familyId',
  getParentRoute: () => rootRoute,
} as any)

const EventsEventIdRoute = EventsEventIdImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdImport
      parentRoute: typeof rootRoute
    }
    '/families/$familyId': {
      id: '/families/$familyId'
      path: '/families/$familyId'
      fullPath: '/families/$familyId'
      preLoaderRoute: typeof FamiliesFamilyIdImport
      parentRoute: typeof rootRoute
    }
    '/individuals/$individualId': {
      id: '/individuals/$individualId'
      path: '/individuals/$individualId'
      fullPath: '/individuals/$individualId'
      preLoaderRoute: typeof IndividualsIndividualIdImport
      parentRoute: typeof rootRoute
    }
    '/places/$placeId': {
      id: '/places/$placeId'
      path: '/places/$placeId'
      fullPath: '/places/$placeId'
      preLoaderRoute: typeof PlacesPlaceIdImport
      parentRoute: typeof rootRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexImport
      parentRoute: typeof rootRoute
    }
    '/families/': {
      id: '/families/'
      path: '/families'
      fullPath: '/families'
      preLoaderRoute: typeof FamiliesIndexImport
      parentRoute: typeof rootRoute
    }
    '/individuals/': {
      id: '/individuals/'
      path: '/individuals'
      fullPath: '/individuals'
      preLoaderRoute: typeof IndividualsIndexImport
      parentRoute: typeof rootRoute
    }
    '/places/': {
      id: '/places/'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/families/$familyId': typeof FamiliesFamilyIdRoute
  '/individuals/$individualId': typeof IndividualsIndividualIdRoute
  '/places/$placeId': typeof PlacesPlaceIdRoute
  '/events': typeof EventsIndexRoute
  '/families': typeof FamiliesIndexRoute
  '/individuals': typeof IndividualsIndexRoute
  '/places': typeof PlacesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/families/$familyId': typeof FamiliesFamilyIdRoute
  '/individuals/$individualId': typeof IndividualsIndividualIdRoute
  '/places/$placeId': typeof PlacesPlaceIdRoute
  '/events': typeof EventsIndexRoute
  '/families': typeof FamiliesIndexRoute
  '/individuals': typeof IndividualsIndexRoute
  '/places': typeof PlacesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/families/$familyId': typeof FamiliesFamilyIdRoute
  '/individuals/$individualId': typeof IndividualsIndividualIdRoute
  '/places/$placeId': typeof PlacesPlaceIdRoute
  '/events/': typeof EventsIndexRoute
  '/families/': typeof FamiliesIndexRoute
  '/individuals/': typeof IndividualsIndexRoute
  '/places/': typeof PlacesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events/$eventId'
    | '/families/$familyId'
    | '/individuals/$individualId'
    | '/places/$placeId'
    | '/events'
    | '/families'
    | '/individuals'
    | '/places'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events/$eventId'
    | '/families/$familyId'
    | '/individuals/$individualId'
    | '/places/$placeId'
    | '/events'
    | '/families'
    | '/individuals'
    | '/places'
  id:
    | '__root__'
    | '/'
    | '/events/$eventId'
    | '/families/$familyId'
    | '/individuals/$individualId'
    | '/places/$placeId'
    | '/events/'
    | '/families/'
    | '/individuals/'
    | '/places/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  FamiliesFamilyIdRoute: typeof FamiliesFamilyIdRoute
  IndividualsIndividualIdRoute: typeof IndividualsIndividualIdRoute
  PlacesPlaceIdRoute: typeof PlacesPlaceIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  FamiliesIndexRoute: typeof FamiliesIndexRoute
  IndividualsIndexRoute: typeof IndividualsIndexRoute
  PlacesIndexRoute: typeof PlacesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  FamiliesFamilyIdRoute: FamiliesFamilyIdRoute,
  IndividualsIndividualIdRoute: IndividualsIndividualIdRoute,
  PlacesPlaceIdRoute: PlacesPlaceIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  FamiliesIndexRoute: FamiliesIndexRoute,
  IndividualsIndexRoute: IndividualsIndexRoute,
  PlacesIndexRoute: PlacesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/events/$eventId",
        "/families/$familyId",
        "/individuals/$individualId",
        "/places/$placeId",
        "/events/",
        "/families/",
        "/individuals/",
        "/places/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/events/$eventId": {
      "filePath": "events/$eventId.tsx"
    },
    "/families/$familyId": {
      "filePath": "families/$familyId.tsx"
    },
    "/individuals/$individualId": {
      "filePath": "individuals/$individualId.tsx"
    },
    "/places/$placeId": {
      "filePath": "places/$placeId.tsx"
    },
    "/events/": {
      "filePath": "events/index.tsx"
    },
    "/families/": {
      "filePath": "families/index.tsx"
    },
    "/individuals/": {
      "filePath": "individuals/index.tsx"
    },
    "/places/": {
      "filePath": "places/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
