create type "public"."gender" as enum ('male', 'female');

create type "public"."name_type" as enum ('birth', 'marriage', 'nickname', 'unknown');

create type "public"."family_type" as enum ('married', 'civil union', 'unknown', 'unmarried');

create table "public"."place_types" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    CONSTRAINT place_types_name_key UNIQUE (name)
);

alter table "public"."place_types" enable row level security;

-- Insert initial place types
INSERT INTO "public"."place_types" ("name") VALUES
('country'),
('state'),
('province'),
('city'),
('town'),
('village'),
('address'),
('cemetery'),
('church'),
('hospital'),
('other');

-- NEW UNIFIED EVENT SYSTEM TABLES

-- Event types (unified)
create table "public"."event_types" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    CONSTRAINT event_types_name_key UNIQUE (name)
);

alter table "public"."event_types" enable row level security;

-- Insert initial event types
INSERT INTO "public"."event_types" ("name") VALUES
('birth'),
('death'),
('marriage'),
('baptism'),
('burial'),
('graduation'),
('immigration'),
('emigration'),
('naturalization'),
('census'),
('will'),
('probate'),
('engagement'),
('divorce'),
('annulment'),
('separation'),
('retirement'),
('other');

-- Event roles
create table "public"."event_roles" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    CONSTRAINT event_roles_name_key UNIQUE (name)
);

alter table "public"."event_roles" enable row level security;

-- Insert initial event roles
INSERT INTO "public"."event_roles" ("name") VALUES
('Subject'),
('Husband'),
('Wife'),
('Deceased'),
('Mother'),
('Father'),
('Witness'),
('Godfather'),
('Godmother'),
('Officiant'),
('Doctor'),
('Midwife'),
('Informant'),
('Guardian'),
('Executor'),
('Beneficiary'),
('Father of Husband'),
('Mother of Husband'),
('Father of Wife'),
('Mother of Wife'),
('Other');

-- Main events table
create table "public"."events" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "type_id" uuid not null,
    "date" text,
    "place_id" uuid,
    "description" text
);

alter table "public"."events" enable row level security;

-- Event subjects (who the event is about)
create table "public"."event_subjects" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "event_id" uuid not null,
    "individual_id" uuid not null
);

alter table "public"."event_subjects" enable row level security;

-- Event participants (everyone involved with roles)
create table "public"."event_participants" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "event_id" uuid not null,
    "individual_id" uuid not null,
    "role_id" uuid not null
);

alter table "public"."event_participants" enable row level security;

create table "public"."families" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "husband_id" uuid,
    "wife_id" uuid,
    "gedcom_id" bigint generated by default as identity not null,
    "type" family_type not null default 'married'::family_type
);

alter table "public"."families" enable row level security;

create table "public"."family_children" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "family_id" uuid not null,
    "individual_id" uuid not null
);

alter table "public"."family_children" enable row level security;

create table "public"."individuals" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "gender" gender not null,
    "gedcom_id" bigint generated by default as identity not null
);

alter table "public"."individuals" enable row level security;

create table "public"."names" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "individual_id" uuid not null,
    "first_name" text,
    "last_name" text,
    "surname" text,
    "type" name_type not null default 'birth'::name_type,
    "is_primary" boolean not null default true
);

alter table "public"."names" enable row level security;

create table "public"."places" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "type_id" uuid not null,
    "parent_id" uuid,
    "latitude" decimal,
    "longitude" decimal
);

alter table "public"."places" enable row level security;

-- CREATE INDEXES

CREATE UNIQUE INDEX families_pkey ON public.families USING btree (id);
CREATE UNIQUE INDEX family_children_pkey ON public.family_children USING btree (id);
CREATE UNIQUE INDEX individuals_gedcom_id_key ON public.individuals USING btree (gedcom_id);
CREATE UNIQUE INDEX individuals_pkey ON public.individuals USING btree (id);
CREATE UNIQUE INDEX names_pkey ON public.names USING btree (id);
CREATE UNIQUE INDEX place_types_pkey ON public.place_types USING btree (id);
CREATE UNIQUE INDEX places_pkey ON public.places USING btree (id);

-- NEW EVENT SYSTEM INDEXES
CREATE UNIQUE INDEX event_types_pkey ON public.event_types USING btree (id);
CREATE UNIQUE INDEX event_roles_pkey ON public.event_roles USING btree (id);
CREATE UNIQUE INDEX events_pkey ON public.events USING btree (id);
CREATE UNIQUE INDEX event_subjects_pkey ON public.event_subjects USING btree (id);
CREATE UNIQUE INDEX event_participants_pkey ON public.event_participants USING btree (id);

-- Performance indexes for event queries
CREATE INDEX events_type_id_idx ON public.events USING btree (type_id);
CREATE INDEX events_date_idx ON public.events USING btree (date);
CREATE INDEX events_place_id_idx ON public.events USING btree (place_id);
CREATE INDEX event_subjects_event_id_idx ON public.event_subjects USING btree (event_id);
CREATE INDEX event_subjects_individual_id_idx ON public.event_subjects USING btree (individual_id);
CREATE INDEX event_participants_event_id_idx ON public.event_participants USING btree (event_id);
CREATE INDEX event_participants_individual_id_idx ON public.event_participants USING btree (individual_id);
CREATE INDEX event_participants_role_id_idx ON public.event_participants USING btree (role_id);

-- ADD PRIMARY KEY CONSTRAINTS

alter table "public"."families" add constraint "families_pkey" PRIMARY KEY using index "families_pkey";
alter table "public"."family_children" add constraint "family_children_pkey" PRIMARY KEY using index "family_children_pkey";
alter table "public"."individuals" add constraint "individuals_pkey" PRIMARY KEY using index "individuals_pkey";
alter table "public"."names" add constraint "names_pkey" PRIMARY KEY using index "names_pkey";
alter table "public"."place_types" add constraint "place_types_pkey" PRIMARY KEY using index "place_types_pkey";
alter table "public"."places" add constraint "places_pkey" PRIMARY KEY using index "places_pkey";

-- NEW EVENT SYSTEM PRIMARY KEYS
alter table "public"."event_types" add constraint "event_types_pkey" PRIMARY KEY using index "event_types_pkey";
alter table "public"."event_roles" add constraint "event_roles_pkey" PRIMARY KEY using index "event_roles_pkey";
alter table "public"."events" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";
alter table "public"."event_subjects" add constraint "event_subjects_pkey" PRIMARY KEY using index "event_subjects_pkey";
alter table "public"."event_participants" add constraint "event_participants_pkey" PRIMARY KEY using index "event_participants_pkey";

-- ADD FOREIGN KEY CONSTRAINTS

alter table "public"."families" add constraint "families_husband_id_fkey" FOREIGN KEY (husband_id) REFERENCES individuals(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."families" validate constraint "families_husband_id_fkey";

alter table "public"."families" add constraint "families_wife_id_fkey" FOREIGN KEY (wife_id) REFERENCES individuals(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."families" validate constraint "families_wife_id_fkey";

alter table "public"."family_children" add constraint "family_children_family_id_fkey" FOREIGN KEY (family_id) REFERENCES families(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."family_children" validate constraint "family_children_family_id_fkey";

alter table "public"."family_children" add constraint "family_children_individual_id_fkey" FOREIGN KEY (individual_id) REFERENCES individuals(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."family_children" validate constraint "family_children_individual_id_fkey";

alter table "public"."individuals" add constraint "individuals_gedcom_id_key" UNIQUE using index "individuals_gedcom_id_key";

alter table "public"."names" add constraint "names_individual_id_fkey" FOREIGN KEY (individual_id) REFERENCES individuals(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."names" validate constraint "names_individual_id_fkey";

alter table "public"."places" add constraint "places_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES places(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."places" validate constraint "places_parent_id_fkey";

alter table "public"."places" add constraint "places_type_id_fkey" FOREIGN KEY (type_id) REFERENCES place_types(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;
alter table "public"."places" validate constraint "places_type_id_fkey";

-- NEW EVENT SYSTEM FOREIGN KEYS
alter table "public"."events" add constraint "events_type_id_fkey" FOREIGN KEY (type_id) REFERENCES event_types(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;
alter table "public"."events" validate constraint "events_type_id_fkey";

alter table "public"."events" add constraint "events_place_id_fkey" FOREIGN KEY (place_id) REFERENCES places(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;
alter table "public"."events" validate constraint "events_place_id_fkey";

alter table "public"."event_subjects" add constraint "event_subjects_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."event_subjects" validate constraint "event_subjects_event_id_fkey";

alter table "public"."event_subjects" add constraint "event_subjects_individual_id_fkey" FOREIGN KEY (individual_id) REFERENCES individuals(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."event_subjects" validate constraint "event_subjects_individual_id_fkey";

alter table "public"."event_participants" add constraint "event_participants_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."event_participants" validate constraint "event_participants_event_id_fkey";

alter table "public"."event_participants" add constraint "event_participants_individual_id_fkey" FOREIGN KEY (individual_id) REFERENCES individuals(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."event_participants" validate constraint "event_participants_individual_id_fkey";

alter table "public"."event_participants" add constraint "event_participants_role_id_fkey" FOREIGN KEY (role_id) REFERENCES event_roles(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;
alter table "public"."event_participants" validate constraint "event_participants_role_id_fkey";

-- GRANT PERMISSIONS

grant delete on table "public"."families" to "anon";
grant insert on table "public"."families" to "anon";
grant references on table "public"."families" to "anon";
grant select on table "public"."families" to "anon";
grant trigger on table "public"."families" to "anon";
grant truncate on table "public"."families" to "anon";
grant update on table "public"."families" to "anon";
grant delete on table "public"."families" to "authenticated";
grant insert on table "public"."families" to "authenticated";
grant references on table "public"."families" to "authenticated";
grant select on table "public"."families" to "authenticated";
grant trigger on table "public"."families" to "authenticated";
grant truncate on table "public"."families" to "authenticated";
grant update on table "public"."families" to "authenticated";
grant delete on table "public"."families" to "service_role";
grant insert on table "public"."families" to "service_role";
grant references on table "public"."families" to "service_role";
grant select on table "public"."families" to "service_role";
grant trigger on table "public"."families" to "service_role";
grant truncate on table "public"."families" to "service_role";
grant update on table "public"."families" to "service_role";

grant delete on table "public"."family_children" to "anon";
grant insert on table "public"."family_children" to "anon";
grant references on table "public"."family_children" to "anon";
grant select on table "public"."family_children" to "anon";
grant trigger on table "public"."family_children" to "anon";
grant truncate on table "public"."family_children" to "anon";
grant update on table "public"."family_children" to "anon";
grant delete on table "public"."family_children" to "authenticated";
grant insert on table "public"."family_children" to "authenticated";
grant references on table "public"."family_children" to "authenticated";
grant select on table "public"."family_children" to "authenticated";
grant trigger on table "public"."family_children" to "authenticated";
grant truncate on table "public"."family_children" to "authenticated";
grant update on table "public"."family_children" to "authenticated";
grant delete on table "public"."family_children" to "service_role";
grant insert on table "public"."family_children" to "service_role";
grant references on table "public"."family_children" to "service_role";
grant select on table "public"."family_children" to "service_role";
grant trigger on table "public"."family_children" to "service_role";
grant truncate on table "public"."family_children" to "service_role";
grant update on table "public"."family_children" to "service_role";

grant delete on table "public"."individuals" to "anon";
grant insert on table "public"."individuals" to "anon";
grant references on table "public"."individuals" to "anon";
grant select on table "public"."individuals" to "anon";
grant trigger on table "public"."individuals" to "anon";
grant truncate on table "public"."individuals" to "anon";
grant update on table "public"."individuals" to "anon";
grant delete on table "public"."individuals" to "authenticated";
grant insert on table "public"."individuals" to "authenticated";
grant references on table "public"."individuals" to "authenticated";
grant select on table "public"."individuals" to "authenticated";
grant trigger on table "public"."individuals" to "authenticated";
grant truncate on table "public"."individuals" to "authenticated";
grant update on table "public"."individuals" to "authenticated";
grant delete on table "public"."individuals" to "service_role";
grant insert on table "public"."individuals" to "service_role";
grant references on table "public"."individuals" to "service_role";
grant select on table "public"."individuals" to "service_role";
grant trigger on table "public"."individuals" to "service_role";
grant truncate on table "public"."individuals" to "service_role";
grant update on table "public"."individuals" to "service_role";

grant delete on table "public"."names" to "anon";
grant insert on table "public"."names" to "anon";
grant references on table "public"."names" to "anon";
grant select on table "public"."names" to "anon";
grant trigger on table "public"."names" to "anon";
grant truncate on table "public"."names" to "anon";
grant update on table "public"."names" to "anon";
grant delete on table "public"."names" to "authenticated";
grant insert on table "public"."names" to "authenticated";
grant references on table "public"."names" to "authenticated";
grant select on table "public"."names" to "authenticated";
grant trigger on table "public"."names" to "authenticated";
grant truncate on table "public"."names" to "authenticated";
grant update on table "public"."names" to "authenticated";
grant delete on table "public"."names" to "service_role";
grant insert on table "public"."names" to "service_role";
grant references on table "public"."names" to "service_role";
grant select on table "public"."names" to "service_role";
grant trigger on table "public"."names" to "service_role";
grant truncate on table "public"."names" to "service_role";
grant update on table "public"."names" to "service_role";

grant delete on table "public"."places" to "anon";
grant insert on table "public"."places" to "anon";
grant references on table "public"."places" to "anon";
grant select on table "public"."places" to "anon";
grant trigger on table "public"."places" to "anon";
grant truncate on table "public"."places" to "anon";
grant update on table "public"."places" to "anon";
grant delete on table "public"."places" to "authenticated";
grant insert on table "public"."places" to "authenticated";
grant references on table "public"."places" to "authenticated";
grant select on table "public"."places" to "authenticated";
grant trigger on table "public"."places" to "authenticated";
grant truncate on table "public"."places" to "authenticated";
grant update on table "public"."places" to "authenticated";
grant delete on table "public"."places" to "service_role";
grant insert on table "public"."places" to "service_role";
grant references on table "public"."places" to "service_role";
grant select on table "public"."places" to "service_role";
grant trigger on table "public"."places" to "service_role";
grant truncate on table "public"."places" to "service_role";
grant update on table "public"."places" to "service_role";

grant delete on table "public"."place_types" to "anon";
grant insert on table "public"."place_types" to "anon";
grant references on table "public"."place_types" to "anon";
grant select on table "public"."place_types" to "anon";
grant trigger on table "public"."place_types" to "anon";
grant truncate on table "public"."place_types" to "anon";
grant update on table "public"."place_types" to "anon";
grant delete on table "public"."place_types" to "authenticated";
grant insert on table "public"."place_types" to "authenticated";
grant references on table "public"."place_types" to "authenticated";
grant select on table "public"."place_types" to "authenticated";
grant trigger on table "public"."place_types" to "authenticated";
grant truncate on table "public"."place_types" to "authenticated";
grant update on table "public"."place_types" to "authenticated";
grant delete on table "public"."place_types" to "service_role";
grant insert on table "public"."place_types" to "service_role";
grant references on table "public"."place_types" to "service_role";
grant select on table "public"."place_types" to "service_role";
grant trigger on table "public"."place_types" to "service_role";
grant truncate on table "public"."place_types" to "service_role";
grant update on table "public"."place_types" to "service_role";

-- NEW EVENT SYSTEM GRANTS

grant delete on table "public"."event_types" to "anon";
grant insert on table "public"."event_types" to "anon";
grant references on table "public"."event_types" to "anon";
grant select on table "public"."event_types" to "anon";
grant trigger on table "public"."event_types" to "anon";
grant truncate on table "public"."event_types" to "anon";
grant update on table "public"."event_types" to "anon";
grant delete on table "public"."event_types" to "authenticated";
grant insert on table "public"."event_types" to "authenticated";
grant references on table "public"."event_types" to "authenticated";
grant select on table "public"."event_types" to "authenticated";
grant trigger on table "public"."event_types" to "authenticated";
grant truncate on table "public"."event_types" to "authenticated";
grant update on table "public"."event_types" to "authenticated";
grant delete on table "public"."event_types" to "service_role";
grant insert on table "public"."event_types" to "service_role";
grant references on table "public"."event_types" to "service_role";
grant select on table "public"."event_types" to "service_role";
grant trigger on table "public"."event_types" to "service_role";
grant truncate on table "public"."event_types" to "service_role";
grant update on table "public"."event_types" to "service_role";

grant delete on table "public"."event_roles" to "anon";
grant insert on table "public"."event_roles" to "anon";
grant references on table "public"."event_roles" to "anon";
grant select on table "public"."event_roles" to "anon";
grant trigger on table "public"."event_roles" to "anon";
grant truncate on table "public"."event_roles" to "anon";
grant update on table "public"."event_roles" to "anon";
grant delete on table "public"."event_roles" to "authenticated";
grant insert on table "public"."event_roles" to "authenticated";
grant references on table "public"."event_roles" to "authenticated";
grant select on table "public"."event_roles" to "authenticated";
grant trigger on table "public"."event_roles" to "authenticated";
grant truncate on table "public"."event_roles" to "authenticated";
grant update on table "public"."event_roles" to "authenticated";
grant delete on table "public"."event_roles" to "service_role";
grant insert on table "public"."event_roles" to "service_role";
grant references on table "public"."event_roles" to "service_role";
grant select on table "public"."event_roles" to "service_role";
grant trigger on table "public"."event_roles" to "service_role";
grant truncate on table "public"."event_roles" to "service_role";
grant update on table "public"."event_roles" to "service_role";

grant delete on table "public"."events" to "anon";
grant insert on table "public"."events" to "anon";
grant references on table "public"."events" to "anon";
grant select on table "public"."events" to "anon";
grant trigger on table "public"."events" to "anon";
grant truncate on table "public"."events" to "anon";
grant update on table "public"."events" to "anon";
grant delete on table "public"."events" to "authenticated";
grant insert on table "public"."events" to "authenticated";
grant references on table "public"."events" to "authenticated";
grant select on table "public"."events" to "authenticated";
grant trigger on table "public"."events" to "authenticated";
grant truncate on table "public"."events" to "authenticated";
grant update on table "public"."events" to "authenticated";
grant delete on table "public"."events" to "service_role";
grant insert on table "public"."events" to "service_role";
grant references on table "public"."events" to "service_role";
grant select on table "public"."events" to "service_role";
grant trigger on table "public"."events" to "service_role";
grant truncate on table "public"."events" to "service_role";
grant update on table "public"."events" to "service_role";

grant delete on table "public"."event_subjects" to "anon";
grant insert on table "public"."event_subjects" to "anon";
grant references on table "public"."event_subjects" to "anon";
grant select on table "public"."event_subjects" to "anon";
grant trigger on table "public"."event_subjects" to "anon";
grant truncate on table "public"."event_subjects" to "anon";
grant update on table "public"."event_subjects" to "anon";
grant delete on table "public"."event_subjects" to "authenticated";
grant insert on table "public"."event_subjects" to "authenticated";
grant references on table "public"."event_subjects" to "authenticated";
grant select on table "public"."event_subjects" to "authenticated";
grant trigger on table "public"."event_subjects" to "authenticated";
grant truncate on table "public"."event_subjects" to "authenticated";
grant update on table "public"."event_subjects" to "authenticated";
grant delete on table "public"."event_subjects" to "service_role";
grant insert on table "public"."event_subjects" to "service_role";
grant references on table "public"."event_subjects" to "service_role";
grant select on table "public"."event_subjects" to "service_role";
grant trigger on table "public"."event_subjects" to "service_role";
grant truncate on table "public"."event_subjects" to "service_role";
grant update on table "public"."event_subjects" to "service_role";

grant delete on table "public"."event_participants" to "anon";
grant insert on table "public"."event_participants" to "anon";
grant references on table "public"."event_participants" to "anon";
grant select on table "public"."event_participants" to "anon";
grant trigger on table "public"."event_participants" to "anon";
grant truncate on table "public"."event_participants" to "anon";
grant update on table "public"."event_participants" to "anon";
grant delete on table "public"."event_participants" to "authenticated";
grant insert on table "public"."event_participants" to "authenticated";
grant references on table "public"."event_participants" to "authenticated";
grant select on table "public"."event_participants" to "authenticated";
grant trigger on table "public"."event_participants" to "authenticated";
grant truncate on table "public"."event_participants" to "authenticated";
grant update on table "public"."event_participants" to "authenticated";
grant delete on table "public"."event_participants" to "service_role";
grant insert on table "public"."event_participants" to "service_role";
grant references on table "public"."event_participants" to "service_role";
grant select on table "public"."event_participants" to "service_role";
grant trigger on table "public"."event_participants" to "service_role";
grant truncate on table "public"."event_participants" to "service_role";
grant update on table "public"."event_participants" to "service_role";

-- ROW LEVEL SECURITY POLICIES

create policy "Enable read access for all users"
on "public"."families"
as permissive
for select
to public
using (true);

create policy "Enable read access for all users"
on "public"."individuals"
as permissive
for select
to public
using (true);

create policy "Enable read access for all users"
on "public"."names"
as permissive
for select
to public
using (true);

create policy "Enable read access for all users"
on "public"."family_children"
as permissive
for select
to public
using (true);

create policy "Enable read access for all users"
on "public"."places"
as permissive
for select
to public
using (true);

create policy "Enable read access for all users"
on "public"."place_types"
as permissive
for select
to public
using (true);

-- NEW EVENT SYSTEM POLICIES

create policy "Enable read access for all users"
on "public"."event_types"
as permissive
for select
to public
using (true);

create policy "Enable read access for all users"
on "public"."event_roles"
as permissive
for select
to public
using (true);

create policy "Enable read access for all users"
on "public"."events"
as permissive
for select
to public
using (true);

create policy "Enable read access for all users"
on "public"."event_subjects"
as permissive
for select
to public
using (true);

create policy "Enable read access for all users"
on "public"."event_participants"
as permissive
for select
to public
using (true);
